export const constants = {
    CREATE_ROOM : 'CREATE_ROOM',
    ROOM_CREATED : 'ROOM_CREATED',
    ROOM_JOINED : 'ROOM_JOINED',
    ROOM_FULL : 'ROOM_FULL',
    ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
    JOIN_ROOM : 'JOIN_ROOM',
    PLAYER_JOINED : 'PLAYER_JOINED',
    UPDATE_SOCKET_ID: 'UPDATE_SOCKET_ID',
    SOCKET_ID_UPDATED: 'SOCKET_ID_UPDATED',
    UPDATE_DB: 'UPDATE_DB',
    DB_UPDATED: 'DB_UPDATED',
}
