export const constants = {
    CREATE_ROOM : 'CREATE_ROOM',
    ROOM_CREATED : 'ROOM_CREATED',
    ROOM_JOINED : 'ROOM_JOINED',
    JOIN_ROOM : 'JOIN_ROOM',
    PLAYER_JOINED : 'PLAYER_JOINED',
    UPDATE_SOCKET_ID: 'UPDATE_SOCKET_ID',
    SOCKET_ID_UPDATED: 'SOCKET_ID_UPDATED',
}
