const ActionTypes = {
    UPDATE_TILE: 'UPDATE_TILE',
    RESET_TILE: 'RESET_TILE',
    CHANGE_PLAYER: 'CHANGE_PLAYER',
    RUN_GAME_LOGIC: 'RUN_GAME_LOGIC',
    EXECUTE_GAME: 'EXECUTE_GAME',
    SHOW_WINNER_MODAL: 'SHOW_WINNER_MODAL' 
}
export default ActionTypes