const ActionTypes = {
    UPDATE_TILE: 'UPDATE_TILE',
    RESET_TILE: 'RESET_TILE',
    CHANGE_PLAYER: 'CHANGE_PLAYER',
    RUN_GAME_LOGIC: 'RUN_GAME_LOGIC',
    EXECUTE_GAME: 'EXECUTE_GAME',
    SHOW_WINNER_MODAL: 'SHOW_WINNER_MODAL',
    SHOW_INPUT_MODAL: 'SHOW_INPUT_MODAL',
    UPDATE_USERINFO: 'UPDATE_USERINFO',
    RESET_GAME: 'RESET_GAME',
    UPDATE_ROOM_ID: 'UPDATE_ROOM_ID',
}
export default ActionTypes
